backend:
  name: github
  repo: JMG1995/gatsby-tailwind-portfolio

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: src/blog
    create: true
    fields:
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
